const pd = [
  {
    title: 'Everything I Never Told You',
    author: 'Celeste Ng',
    image: 'https://i.imgur.com/Z3KCXEx.png',
    price: 10,
  },
  {
    title: "The Magician's Daughter",
    author: 'H. G. Parry',
    image: 'https://i.imgur.com/ouqRZUK.png',
    price: 10,
  },
  {
    title: "Harry Potter and thee Sorcerer's Stone",
    author: 'J.K. Rowling',
    image: 'https://i.imgur.com/UPlKGeM.png',
    price: 10,
  },
  {
    title: 'Birds of California',
    author: 'Katie Cotugno',
    image: 'https://i.imgur.com/aZkFW4C.png',
    price: 10,
  },
  {
    title: "Dava Shastri's Last Day",
    author: 'Kirthana Ramisetti',
    image: 'https://i.imgur.com/qJYvsCs.png',
    price: 10,
  },
  {
    title: 'Beautiful Boards',
    author: 'Maegan Brown',
    image: 'https://i.imgur.com/ep2EhkV.png',
    price: 10,
  },
  {
    title: "Harry Potter and thee Sorcerer's Stone",
    author: 'J.K. Rowling',
    image: 'https://i.imgur.com/UPlKGeM.png',
    price: 10,
  },
  {
    title: 'The Magnolia Bakery Handbook',
    author: 'Bobbie Lloyd',
    image: 'https://i.imgur.com/BShUox0.png',
    price: 10,
  },
  {
    title: 'Other Birds',
    author: 'Sarah Addison Allen',
    image: 'https://i.imgur.com/zaIwfW6.png',
    price: 10,
  },
  {
    title: 'Mooncakes and Milk Bread',
    author: 'Kristina Cho',
    image: 'https://i.imgur.com/IVIaCOy.png',
    price: 10,
  },
  {
    title: 'Lessons in Chemistry',
    author: 'Bonnie Garmus',
    image: 'https://i.imgur.com/8ao36Kt.png',
    price: 10,
  },
  {
    title: 'The Night Ship',
    author: 'Jess Kidd',
    image: 'https://i.imgur.com/hw4Gved.png',
    price: 10,
  },
  {
    title: 'One Italian Summer',
    author: 'Rebecca Serle',
    image: 'https://i.imgur.com/IC0Io16.png',
    price: 10,
  },
  {
    title: 'Pineapple Street',
    author: 'Jenny Jackson',
    image: 'https://i.imgur.com/725DGGC.png',
    price: 10,
  },
  {
    title: 'The Sister Effect',
    author: 'Susan Mallery',
    image: 'https://i.imgur.com/lmxA2pu.png',
    price: 10,
  },
  {
    title: 'Woman on Fire',
    author: 'Lisa Barr',
    image: 'https://i.imgur.com/xHpksGy.png',
    price: 10,
  },
  {
    title: 'The Fault in Our Stars',
    author: 'John Green',
    image: 'https://i.imgur.com/MA7NDtv.png',
    price: 15,
  },
  {
    title: 'Of Mice and Men',
    author: 'John Steinbeck',
    image: 'https://i.imgur.com/KKfLTgu.png',
    price: 17,
  },

  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    image: 'https://i.imgur.com/I1ix7us.png',
    price: 15,
  },

  {
    title: '1984',
    author: 'George Orwell',
    image: 'https://i.imgur.com/cJdclwr.png',
    price: 10,
  },
  {
    title: "Harry Potter and thee Sorcerer's Stone",
    author: 'J.K. Rowling',
    image: 'https://i.imgur.com/UPlKGeM.png',
    price: 10,
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    image: 'https://i.imgur.com/iohvDZ7.png',
    price: 10,
  },
  {
    title: 'The Great Gatsby',
    author: ' F. Scott Fitzgerald',
    image: 'https://i.imgur.com/ga5EhD2.png',
    price: 10,
  },
  {
    title: "Charlotte's Web",
    author: 'E.B. White',
    image: 'https://i.imgur.com/I15cGDp.png',
    price: 10,
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    image: 'https://i.imgur.com/8kqhbZT.png',
    price: 10,
  },
  {
    title: 'Little Women',
    author: 'Louisa May Alcott',
    image: 'https://i.imgur.com/94JE65T.png',
    price: 10,
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    image: 'https://i.imgur.com/nSYCnXv.png',
    price: 10,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Bronte',
    image: 'https://i.imgur.com/xhiJcsm.png',
    price: 10,
  },
  {
    title: 'Gone with the Wind',
    author: 'Margaret Mitchell',
    image: 'https://i.imgur.com/uByKROf.png',
    price: 10,
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    image: 'https://i.imgur.com/dB1fOMz.png',
    price: 10,
  },
  {
    title: 'The Book Thief',
    author: 'Markus Zusak',
    image: 'https://i.imgur.com/pwXwTUg.png',
    price: 10,
  },
  {
    title: 'Great Expectations',
    author: 'Charles Dickens',
    image: 'https://i.imgur.com/1ClMORe.png',
    price: 10,
  },
  {
    title: 'Life of Pi',
    author: 'Yann Martel',
    image: 'https://i.imgur.com/SZmT1Gd.png',
    price: 10,
  },
];

module.exports = pd;
